#!/bin/sh

cat << end > /etc/nginx/sites-available/default
server {
       listen 443 ssl;
		ssl_protocols TLSv1.3;
		ssl_certificate /etc/nginx/ssl/my_private_certif.crt;
		ssl_certificate_key /etc/nginx/ssl/my_private_key.key;
        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.php index.html index.htm index.nginx-debian.html;

        # server_name _;
        server_name $LOGIN www.$LOGIN;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

        # pass PHP scripts to FastCGI server
        #
        location ~ \.php$ {
              include snippets/fastcgi-php.conf;
        
              # With php-fpm (or other unix sockets):
              # With php-cgi (or other tcp sockets):
              fastcgi_pass wordpress:9000;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}
end
# service nginx start
# service nginx stop;
# exec nginx -g 'daemon off;'
# nginx -s reload
# service nginx reload
# service nginx restart